#!/bin/sh
set -e

# Config em runtime: gera config.js a partir de variáveis de ambiente
# para que o frontend use a API correta sem rebuild.
API_BASE_URL="${VITE_API_BASE_URL:-http://localhost:8080}"
API_KEY="${VITE_API_KEY:-}"

cat > /usr/share/nginx/html/config.js << EOF
window.__RUNTIME_CONFIG__ = {
  apiBaseUrl: "${API_BASE_URL}",
  apiKey: "${API_KEY}"
};
EOF

# ── Security headers snippet ─────────────────────────────────────────────────
# Build the Content-Security-Policy connect-src list.
# Set FERRESDB_API_URL to allow the frontend to reach a specific API origin
# (e.g. FERRESDB_API_URL=https://api.example.com).
# WebSocket origins (ws: wss:) are always included for real-time updates.
FERRESDB_API_URL="${FERRESDB_API_URL:-}"
CONNECT_EXTRA=""
if [ -n "$FERRESDB_API_URL" ]; then
    CONNECT_EXTRA="$FERRESDB_API_URL "
fi

CSP="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' ${CONNECT_EXTRA}ws: wss:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"

mkdir -p /etc/nginx/snippets
cat > /etc/nginx/snippets/security_headers.conf << NGINX
# Generated by docker-entrypoint.sh — do not edit manually
add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "same-origin" always;
add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
add_header Content-Security-Policy "${CSP}" always;
NGINX

exec "$@"
